"""
Module de lookup parti/groupe parlementaire pour les sénateurs.
Compatible Python 3.9+
"""

from typing import Optional

SENATORS_DATA = {
    ("AESCHLIMANN", "Marie-Do"): ("Les Républicains", "Groupe Les Républicains"),
    ("ALLIZARD", "Pascal"): ("Les Républicains", "Groupe Les Républicains"),
    ("ANGLARS", "Jean-Claude"): ("Les Républicains", "Groupe Les Républicains"),
    ("ANTOINE", "Jocelyne"): ("Union Centriste", "Groupe Union Centriste"),
    ("APOURCEAU-POLY", "Cathy"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("ARNAUD", "Jean-Michel"): ("Union Centriste", "Groupe Union Centriste"),
    ("ARTIGALAS", "Viviane"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BACCHI", "Jérémy"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("BAC", "Jean"): ("Les Républicains", "Groupe Les Républicains"),
    ("BARROS", "Pierre"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("BASQUIN", "Alexandre"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("BAZIN", "Arnaud"): ("Les Républicains", "Groupe Les Républicains"),
    ("BÉLIM", "Audrey"): ("Divers gauche", "Groupe Socialiste, Écologiste et Républicain"),
    ("BELIN", "Bruno"): ("Les Républicains", "Groupe Les Républicains"),
    ("BELLAMY", "Marie-Jeanne"): ("Les Républicains", "Groupe Les Républicains"),
    ("BELLUROT", "Nadine"): ("Les Républicains", "Groupe Les Républicains"),
    ("BELRHITI", "Catherine"): ("Les Républicains", "Groupe Les Républicains"),
    ("BENARROCHE", "Guy"): ("Les Écologistes", "Groupe Écologiste - Solidarité et Territoires"),
    ("BERTHET", "Martine"): ("Les Républicains", "Groupe Les Républicains"),
    ("BESSIN-GUÉRIN", "Marie-Pierre"): ("Horizons", "Groupe Les Indépendants - République et Territoires"),
    ("BILHAC", "Christian"): ("Alliance Centriste", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("BILLON", "Annick"): ("Union Centriste", "Groupe Union Centriste"),
    ("BITZ", "Olivier"): ("Horizons", "Groupe Union Centriste"),
    ("BLANC", "Étienne"): ("Les Républicains", "Groupe Les Républicains"),
    ("BLANC", "Grégory"): ("Les Écologistes", "Groupe Écologiste - Solidarité et Territoires"),
    ("BLANC", "Jean-Baptiste"): ("Les Républicains", "Groupe Les Républicains"),
    ("BLATRIX CONTAT", "Florence"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BLEUNVEN", "Yves"): ("Union Centriste", "Groupe Union Centriste"),
    ("BONFANTI-DOSSAT", "Christine"): ("Les Républicains", "Groupe Les Républicains"),
    ("BONHOMME", "François"): ("Les Républicains", "Groupe Les Républicains"),
    ("BONNEAU", "François"): ("Union Centriste", "Groupe Union Centriste"),
    ("BONNEFOY", "Nicole"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BONNUS", "Michel"): ("Les Républicains", "Groupe Les Républicains"),
    ("BORCHIO FONTIMP", "Alexandra"): ("Les Républicains", "Groupe Les Républicains"),
    ("BOUAD", "Denis"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BOURCIER", "Corinne"): ("Horizons", "Groupe Les Indépendants - République et Territoires"),
    ("BOURGI", "Hussein"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BOURGUIGNON", "Brigitte"): ("Ensemble !", "Groupe Union Centriste"),
    ("BOYER", "Jean-Marc"): ("Les Républicains", "Groupe Les Républicains"),
    ("BOYER", "Valérie"): ("Les Républicains", "Groupe Les Républicains"),
    ("BRAULT", "Jean-Luc"): ("Horizons", "Groupe Les Indépendants - République et Territoires"),
    ("BRIANTE GUILLEMONT", "Sophie"): ("Alliance Centriste", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("BRIQUET", "Isabelle"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BRISSON", "Max"): ("Les Républicains", "Groupe Les Républicains"),
    ("BROSSAT", "Ian"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("BROSSEL", "Colombe"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("BRULIN", "Céline"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("BRUYEN", "Christian"): ("Les Républicains", "Groupe Les Républicains"),
    ("BUFFET", "François-Noël"): ("Les Républicains", "Groupe Les Républicains"),
    ("BUIS", "Bernard"): ("Ensemble !", "Groupe Rassemblement des démocrates, progressistes et indépendants"),
    ("BURGOA", "Laurent"): ("Les Républicains", "Groupe Les Républicains"),
    ("CABANEL", "Henri"): ("Parti Radical de Gauche", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("CADEC", "Alain"): ("Les Républicains", "Groupe Les Républicains"),
    ("CAMBIER", "Guislain"): ("Les Républicains", "Groupe Les Républicains"),
    ("CANEVET", "Michel"): ("Union Centriste", "Groupe Union Centriste"),
    ("CARDON", "Rémi"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("CARTRON", "Françoise"): ("Parti Radical de Gauche", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("CASTELLI", "Joseph"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("CAZABONNE", "Alain"): ("Union Centriste", "Groupe Union Centriste"),
    ("CAZEAU", "Bernard"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("CHAIZE", "Patrick"): ("Les Républicains", "Groupe Les Républicains"),
    ("CHASSEING", "Daniel"): ("Les Républicains", "Groupe Les Républicains"),
    ("CHATILLON", "Alain"): ("Les Républicains", "Groupe Les Républicains"),
    ("CHAUVIN", "Isabelle"): ("Union Centriste", "Groupe Union Centriste"),
    ("CHAZAL", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("CHOLVY", "Laurent"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("CLÉMENT", "Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("COMTE", "Éric"): ("Les Républicains", "Groupe Les Républicains"),
    ("CORBIN", "Jean-Pierre"): ("Parti Progressiste Martiniquais", "Groupe Socialiste, Écologiste et Républicain"),
    ("COSTE", "Josiane"): ("Union Centriste", "Groupe Union Centriste"),
    ("COURTEAU", "Roland"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("CRISNARD", "Alain"): ("Les Républicains", "Groupe Les Républicains"),
    ("CULLAFROY", "Jean-Pierre"): ("Divers gauche", "Groupe Socialiste, Écologiste et Républicain"),
    ("DARNAUD", "Mathieu"): ("Les Républicains", "Groupe Les Républicains"),
    ("DAUDIGNY", "Yves"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("DAUNIS", "Marc"): ("Les Républicains", "Groupe Les Républicains"),
    ("DE MONTGOLFIER", "Albéric"): ("Les Républicains", "Groupe Les Républicains"),
    ("DECOOL", "Jean-Philippe"): ("Divers centre", "Groupe Les Indépendants - République et Territoires"),
    ("DELCROS", "Bernard"): ("Union Centriste", "Groupe Union Centriste"),
    ("DELATTRE", "Nathalie"): ("Union Centriste", "Groupe Union Centriste"),
    ("DELEY", "Jean-François"): ("Les Républicains", "Groupe Les Républicains"),
    ("DELNEST", "Thierry"): ("Les Républicains", "Groupe Les Républicains"),
    ("DÉRIOT", "Gérard"): ("Les Républicains", "Groupe Les Républicains"),
    ("DESEYNE", "Chantal"): ("Les Républicains", "Groupe Les Républicains"),
    ("DEVINAZ", "Gilbert-Luc"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("DI FOLCO", "Catherine"): ("Les Républicains", "Groupe Les Républicains"),
    ("DOUAY", "Valérie"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("DUBOIS", "Vincent"): ("Les Républicains", "Groupe Les Républicains"),
    ("DUFAUT", "Jean-Claude"): ("Les Républicains", "Groupe Les Républicains"),
    ("DUHAMEL", "Jean-Marie"): ("Union Centriste", "Groupe Union Centriste"),
    ("DUPONT", "Catherine"): ("Les Républicains", "Groupe Les Républicains"),
    ("DURANTON", "Nicole"): ("Les Républicains", "Groupe Les Républicains"),
    ("DURAN", "Alain"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("DURANTON", "Philippe"): ("Les Républicains", "Groupe Les Républicains"),
    ("ESTROSI SASSONE", "Dominique"): ("Les Républicains", "Groupe Les Républicains"),
    ("FÉRET", "Corinne"): ("Les Républicains", "Groupe Les Républicains"),
    ("FICHET", "Jean-Luc"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("FILLEUL", "Corinne"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("FOUCAULT", "Éric"): ("Les Républicains", "Groupe Les Républicains"),
    ("FRASSA", "Robert"): ("Les Républicains", "Groupe Les Républicains"),
    ("GARRIGUE", "Jean-Marc"): ("Union Centriste", "Groupe Union Centriste"),
    ("GAY", "Fabien"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("GENEST", "Jacques"): ("Les Républicains", "Groupe Les Républicains"),
    ("GHALI", "Samia"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("GILLES", "Bruno"): ("Les Républicains", "Groupe Les Républicains"),
    ("GILLÉ", "Hervé"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("GIUDICELLI", "Colette"): ("Les Républicains", "Groupe Les Républicains"),
    ("GOY-CHAVENT", "Sylvie"): ("Union Centriste", "Groupe Union Centriste"),
    ("GRIGNY", "Éric"): ("Les Républicains", "Groupe Les Républicains"),
    ("GROS", "Jean"): ("Les Républicains", "Groupe Les Républicains"),
    ("GROSPERRIN", "Jacques"): ("Les Républicains", "Groupe Les Républicains"),
    ("GRUNY", "Pascale"): ("Les Républicains", "Groupe Les Républicains"),
    ("GUÉRINI", "Jean-Noël"): ("Divers centre", "Groupe Rassemblement des démocrates, progressistes et indépendants"),
    ("GUHL", "Antoinette"): ("Les Écologistes", "Groupe Écologiste - Solidarité et Territoires"),
    ("GUIDEZ", "Jocelyne"): ("Union Centriste", "Groupe Union Centriste"),
    ("GUILLOTIN", "Véronique"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("HARRIBEY", "Laurence"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("HOUPERT", "Alain"): ("Les Républicains", "Groupe Les Républicains"),
    ("HURÉ", "Benoît"): ("Les Républicains", "Groupe Les Républicains"),
    ("IMBERT", "Corinne"): ("Les Républicains", "Groupe Les Républicains"),
    ("JACQUES", "Alain"): ("Les Républicains", "Groupe Les Républicains"),
    ("JEANSANNETAS", "Éric"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("JOUFFROY", "Daniel"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("JOURDA", "Gisèle"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("JOUVIN", "Marie-Christine"): ("Les Républicains", "Groupe Les Républicains"),
    ("KANNER", "Patrick"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("LABORDE", "Françoise"): ("Parti Radical de Gauche", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("LAHELLEC", "Gérard"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("LAMÉNIE", "Marc"): ("Les Républicains", "Groupe Les Républicains"),
    ("LARCHER", "Gérard"): ("Les Républicains", "Groupe Les Républicains"),
    ("LASSARADE", "Florence"): ("Les Républicains", "Groupe Les Républicains"),
    ("LAURENT", "Daniel"): ("Les Républicains", "Groupe Les Républicains"),
    ("LAVARDE", "Christine"): ("Les Républicains", "Groupe Les Républicains"),
    ("LEFÈVRE", "Antoine"): ("Les Républicains", "Groupe Les Républicains"),
    ("LELEUX", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("LEROUX", "Jean-Marie"): ("Les Républicains", "Groupe Les Républicains"),
    ("LEROY", "Henri"): ("Les Républicains", "Groupe Les Républicains"),
    ("LESCANNE", "Éric"): ("Les Républicains", "Groupe Les Républicains"),
    ("LHERBIER", "Éric"): ("Les Républicains", "Groupe Les Républicains"),
    ("LONGEOT", "Jean-François"): ("Union Centriste", "Groupe Union Centriste"),
    ("LOPEZ", "Vivette"): ("Les Républicains", "Groupe Les Républicains"),
    ("LOZACH", "Jean-Jacques"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("LUCAS", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("LUCHE", "Jean-Claude"): ("Union Centriste", "Groupe Union Centriste"),
    ("MAHÉ", "Véronique"): ("Les Républicains", "Groupe Les Républicains"),
    ("MALHURET", "Claude"): ("Horizons", "Groupe Les Indépendants - République et Territoires"),
    ("MARC", "Alain"): ("Union Centriste", "Groupe Union Centriste"),
    ("MARSEILLE", "Hervé"): ("Union Centriste", "Groupe Union Centriste"),
    ("MARTIN", "Didier"): ("Les Républicains", "Groupe Les Républicains"),
    ("MAUREY", "Hervé"): ("Les Républicains", "Groupe Les Républicains"),
    ("MAZUIR", "Rachel"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("MÉDEVIELLE", "Pierre"): ("Union Centriste", "Groupe Union Centriste"),
    ("MENONVILLE", "Franck"): ("Union Centriste", "Groupe Union Centriste"),
    ("MÉZARD", "Jacques"): ("Parti Radical de Gauche", "Groupe du Rassemblement Démocratique et Social Européen"),
    ("MICOULEAU", "Brigitte"): ("Les Républicains", "Groupe Les Républicains"),
    ("MICHALET", "Éric"): ("Union Centriste", "Groupe Union Centriste"),
    ("MICHAU", "Jean-Jacques"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("MOINARD", "Philippe"): ("Les Républicains", "Groupe Les Républicains"),
    ("MONTAUGÉ", "Franck"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("MORA", "Jean"): ("Les Républicains", "Groupe Les Républicains"),
    ("MORHET-RICHAUD", "Patricia"): ("Les Républicains", "Groupe Les Républicains"),
    ("MOUILLER", "Brigitte"): ("Les Républicains", "Groupe Les Républicains"),
    ("NATUREL", "Georges"): ("Divers droite", "Groupe Les Républicains"),
    ("NOËL", "Sylviane"): ("Les Républicains", "Groupe Les Républicains"),
    ("NOUGEIN", "Claude"): ("Les Républicains", "Groupe Les Républicains"),
    ("OMAR OILI", "Saïd"): ("Divers gauche", "Groupe Socialiste, Écologiste et Républicain"),
    ("PANUNZI", "Jean-Jacques"): ("Les Républicains", "Groupe Les Républicains"),
    ("PATRIAT", "François"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("PAUL", "Philippe"): ("Les Républicains", "Groupe Les Républicains"),
    ("PERRIN", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("PERRUT", "Bernard"): ("Les Républicains", "Groupe Les Républicains"),
    ("PERROT", "Évelyne"): ("Les Républicains", "Groupe Les Républicains"),
    ("POINTEREAU", "Rémy"): ("Les Républicains", "Groupe Les Républicains"),
    ("PONIATOWSKI", "Ladislas"): ("Les Républicains", "Groupe Les Républicains"),
    ("PORTELLI", "Hugues"): ("Les Républicains", "Groupe Les Républicains"),
    ("PRUNAUD", "Christine"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("RAMOND", "Françoise"): ("Les Républicains", "Groupe Les Républicains"),
    ("RAYNAL", "Claude"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("REILHAC", "Jean-François"): ("Les Républicains", "Groupe Les Républicains"),
    ("RENAUD-GARNIER", "Véronique"): ("Union Centriste", "Groupe Union Centriste"),
    ("RETAILLEAU", "Bruno"): ("Les Républicains", "Groupe Les Républicains"),
    ("RICHER", "Marie-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("RIVET", "Jean-Claude"): ("Les Républicains", "Groupe Les Républicains"),
    ("ROBERT", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("ROUX", "Jean-Yves"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("ROYER", "Jean"): ("Les Républicains", "Groupe Les Républicains"),
    ("SAINT-PÉ", "Franck"): ("Union Centriste", "Groupe Union Centriste"),
    ("SCHMITZ", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("SEGOUIN", "Isabelle"): ("Les Républicains", "Groupe Les Républicains"),
    ("SÉNÉ", "Laurence"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
    ("SOL", "Patricia"): ("Les Républicains", "Groupe Les Républicains"),
    ("SUTOUR", "Simon"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("TAMARELLE", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("THOMAS", "Claudine"): ("Les Républicains", "Groupe Les Républicains"),
    ("TOURENNE", "Jean-Pierre"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("VALL", "Raymond"): ("Union Centriste", "Groupe Union Centriste"),
    ("VALLAUD", "Pierre"): ("Parti Socialiste", "Groupe Socialiste, Écologiste et Républicain"),
    ("VASPART", "Michel"): ("Les Républicains", "Groupe Les Républicains"),
    ("VÉRIEN", "Dominique"): ("Union Centriste", "Groupe Union Centriste"),
    ("VERMEILLET", "Sylvie"): ("Union Centriste", "Groupe Union Centriste"),
    ("VERZELEN", "Pierre-Jean"): ("Les Républicains", "Groupe Les Républicains"),
    ("VIAL", "Cédric"): ("Les Républicains", "Groupe Les Républicains"),
    ("VILLANI", "Cédric"): ("Divers centre", "Groupe Rassemblement des démocrates, progressistes et indépendants"),
    ("VOGEL", "Mélanie"): ("Les Écologistes", "Groupe Écologiste - Solidarité et Territoires"),
    ("VOGEL", "Jean-Pierre"): ("Les Républicains", "Groupe Les Républicains"),
    ("ZIANE", "Adel"): ("Parti Communiste Français", "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky"),
}

GROUP_SHORT = {
    "Groupe Les Républicains": "LR",
    "Groupe Union Centriste": "UC",
    "Groupe Socialiste, Écologiste et Républicain": "SER",
    "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky": "CRCE-K",
    "Groupe Écologiste - Solidarité et Territoires": "EST",
    "Groupe du Rassemblement Démocratique et Social Européen": "RDSE",
    "Groupe Rassemblement des démocrates, progressistes et indépendants": "RDPI",
    "Groupe Les Indépendants - République et Territoires": "LIRT",
}

GROUP_EMOJI = {
    "Groupe Les Républicains": "🔵",
    "Groupe Union Centriste": "🟠",
    "Groupe Socialiste, Écologiste et Républicain": "🌹",
    "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky": "🔴",
    "Groupe Écologiste - Solidarité et Territoires": "🌿",
    "Groupe du Rassemblement Démocratique et Social Européen": "🟡",
    "Groupe Rassemblement des démocrates, progressistes et indépendants": "🟣",
    "Groupe Les Indépendants - République et Territoires": "⚪",
}

GROUP_HASHTAG = {
    "Groupe Les Républicains": "LesRepublicains",
    "Groupe Union Centriste": "UnionCentriste",
    "Groupe Socialiste, Écologiste et Républicain": "GroupeSER",
    "Groupe Communiste Républicain Citoyen et Écologiste - Kanaky": "CRCE",
    "Groupe Écologiste - Solidarité et Territoires": "Ecologistes",
    "Groupe du Rassemblement Démocratique et Social Européen": "RDSE",
    "Groupe Rassemblement des démocrates, progressistes et indépendants": "RDPI",
    "Groupe Les Indépendants - République et Territoires": "LesIndependants",
}

SENATOR_HANDLES = {
    "JADOT Yannick": "@yjadot.bsky.social",
    "CARDON Rémi": "@cardon.bsky.social",
    "FÉRAUD Rémi": "@remiferaud.bsky.social",
    "GONTARD Guillaume": "@guillaume-gontard.fr",
    "OUIZILLE Alexandre": "@alexandreouizille.fr",
    "DOSSUS Thomas": "@thomasdossus.fr",
    "OUZOULIAS Pierre": "@pierreouzoulias.bsky.social",
    "JOMIER Bernard": "@bernardjomier.bsky.social",
    "MALHURET Claude": "@claudemalhuret.bsky.social",
    "PLA Sébastien": "@sebastienpla.bsky.social",
    "SALMON Daniel": "@danielsalmon.bsky.social",
    "GAY Fabien": "@fabien-gay.fr",
    "BENARROCHE Guy": "@guybenarroche.bsky.social",
    "TEMAL Rachid": "@rachidtemal.bsky.social",
    "KANNER Patrick": "@patrickkanner.bsky.social",
    "LUREL Victorin": "@victorinlurel.bsky.social",
    "FERNIQUE Jacques": "@jacquesfernique.bsky.social",
    "BLANC Grégory": "@gregoryblanc49.bsky.social",
    "WEBER Michaël": "@webermichael.bsky.social",
    "DANTEC Ronan": "@ronandantec.bsky.social",
    "FAGNEN Sébastien": "@sfagnen.bsky.social",
    "DURAIN Jérôme": "@jerome-durain.bsky.social",
    "MELLOULI Akli": "@aklim.bsky.social",
    "IACOVELLI Xavier": "@iacoxav.bsky.social",
    "MARIE Didier": "@didiermarie.bsky.social",
    "BACCHI Jérémy": "@jeremybacchi.bsky.social",
    "VAYSSOUZE-FAURE Jean-Marc": "@jmvayssouze.bsky.social",
    "CHANTREL Yan": "@yanchantrel.bsky.social",
    "VALLET Mickaël": "@mickaelvallet.bsky.social",
    "HERVÉ Loïc": "@loicherve.bsky.social",
    "ROS David": "@davidros91.bsky.social",
    "COZIC Thierry": "@thcozic.bsky.social",
    "CHAILLOU Christophe": "@c-chaillou.bsky.social",
    "BLANC Jean-Baptiste": "@jbblanc84.bsky.social",
    "BARROS Pierre": "@pierrebarros.bsky.social",
    "BRIANTE GUILLEMONT Sophie": "@sbg-senat.bsky.social",
    "BROSSEL Colombe": "@cbrossel.bsky.social",
    "CANALÈS Marion": "@marioncanales.bsky.social",
    "CARRERE-GEE Marie-Claire": "@m-c-c-g.bsky.social",
    "CONWAY-MOURET Hélène": "@hconwaymouret.bsky.social",
    "CUKIERMAN Cécile": "@cecilecukierman.bsky.social",
    "DE MARCO Monique": "@moniquedemarco.bsky.social",
    "ESPAGNAC Frédérique": "@fespagnac.bsky.social",
    "FLORENNES Isabelle": "@iflrns92.bsky.social",
    "GUHL Antoinette": "@antoinetteguhl.bsky.social",
    "LE HOUÉROU Annie": "@annielehouerou.bsky.social",
    "LINKENHELD Audrey": "@audreylinkenheld.bsky.social",
    "MORIN DESAILLY Catherine": "@cmorindesailly.bsky.social",
    "NARASSIGUIN Corinne": "@corinnenara.bsky.social",
    "OLLIVIER Mathilde": "@mathildeollivier.bsky.social",
    "PONCET MONGE Raymonde": "@raymondeponcet.bsky.social",
    "ROSSIGNOL Laurence": "@laurossignol.bsky.social",
    "SENÉE Ghislaine": "@ghislainesenee.bsky.social",
    "SOUYRIS Anne": "@annesouyris.bsky.social",
    "VARAILLAS Marie-Claude": "@mcvaraillas.bsky.social",
    "VÉRIEN Dominique": "@dominiqueverien.bsky.social",
    "VOGEL Mélanie": "@melanievogel.bsky.social",
}


def lookup_senator(nom, prenom):
    # type: (str, str) -> Optional[dict]
    key = (nom.strip().upper(), prenom.strip())
    data = SENATORS_DATA.get(key)
    if data:
        parti, groupe = data
        handle_key = "{} {}".format(nom.strip().upper(), prenom.strip())
        handle = SENATOR_HANDLES.get(handle_key)
        return {
            "parti": parti,
            "groupe": groupe,
            "groupe_court": GROUP_SHORT.get(groupe, groupe),
            "emoji": GROUP_EMOJI.get(groupe, "🏛️"),
            "hashtag": "#" + GROUP_HASHTAG.get(groupe, groupe.replace(" ", "")),
            "handle": handle,  # None si pas de compte Bluesky connu
        }
    return None


def format_political_line(nom, prenom, short=False):
    # type: (str, str, bool) -> str
    info = lookup_senator(nom, prenom)
    if not info:
        return ""
    if short:
        return "{} {}".format(info["emoji"], info["groupe_court"])
    return "{} {} · {}".format(info["emoji"], info["groupe_court"], info["groupe"])
